build:
 version: "2.0"
 
accounts:
  message: "Welcome to QA EazyBank Cards related to local API's"
  contactDetails: 
    name: "JohnDoe -Developer"
    email: "shanthipillai@gmail.com"
  onCallSupport: 
    -(555) 555-123-1234
    -(555) 523-134-3456