server:
  port: 8071
spring:
  application:
    name: "configserver"
  profiles:
    #active: native 
    active: git 
  cloud: 
    config: 
      server:
       # native: 
          #search-locations: "classpath:/config"
          #search-locations: "file:///E://config"
         git: 
           uri: "https://github.com/shanthipillai/ConfigServerRepoProjectWork.git"
           default-lable: master
           timeout: 5
           clone-on-start: true
           force-pull: true
encrypt:
  key: "fgrreyGRGREG1245FDGDFG$#"
  
management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
  